server:
  port: 8111

#    配置spring-security的用户名密码--方式一--配置文件
#spring:
#  security:
#    user:
#      name: lucy
#      password: 123

spring:
  thymeleaf:
    cache: false
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://****?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ***